version: "3"
services:
    app:
        image: stevenhvtran/kv-app:v0.1
        ports:
            - "5000:5000"
        volumes:
            - "./app.py:/usr/src/app/app.py"
        environment:
            - FLASK_APP=app.py
            - FLASK_ENV=development
            - REDIS_URL=redis
    redis:
        image: redis:alpine
        volumes:
            - "redis-data:/data"
        expose:
            - "6379"
volumes:
    redis-data:
